const fs = require('fs');
const lines = [
  "import React, { useState } from 'react';",
  "import { StyleSheet, Text, View, TextInput, TouchableOpacity, ScrollView, SafeAreaView, Platform } from 'react-native';",
  "export default function App() {",
  "  const [phone, setPhone] = useState('');",
  "  const [otp, setOtp] = useState('');",
  "  const [step, setStep] = useState('PHONE');",
  "  return (",
  "    ",
  "      ",
  "        Gebeya Retail",
  "        Adama B2B Wholesale Hub",
  "        {step === 'PHONE' ? (",
  "          ",
  "            Phone Number",
  "            ",
  "             setStep('OTP')}>",
  "              Continue",
  "            ",
  "          ",
  "        ) : (",
  "          ",
  "            Enter 4-Digit OTP",
  "            ",
  "              Sign In",
  "            ",
  "          ",
  "        )}",
  "      ",
  "    ",
  "  );",
  "}",
  "const styles = StyleSheet.create({",
  "  container: { flex: 1, backgroundColor: '#F5F7F3' },",
  "  center: { flexGrow: 1, justifyContent: 'center', alignItems: 'center', padding: 20 },",
  "  title: { fontSize: 32, fontWeight: 'bold', color: '#0F7B4A' },",
  "  subtitle: { fontSize: 14, color: '#62726A', marginBottom: 24 },",
  "  card: { width: '100%', maxWidth: 360, gap: 12 },",
  "  label: { fontSize: 14, fontWeight: '600', color: '#12241A' },",
  "  input: { height: 50, borderWidth: 1.5, borderColor: '#DDE4DD', borderRadius: 10, paddingHorizontal: 16, backgroundColor: '#FFF' },",
  "  btn: { height: 50, backgroundColor: '#0F7B4A', borderRadius: 10, justifyContent: 'center', alignItems: 'center' },",
  "  btnText: { color: '#FFF', fontSize: 16, fontWeight: 'bold' },",
  "});"
];
fs.writeFileSync('App.js', lines.join('\n'), 'utf8');
