export const STRINGS = {
  appName: 'ገበያ',
  subTitle: 'የአዳማ ኪዮስኮችና ቸርቻሪዎች የጅምላ ማዘዣ',
  phoneLabel: 'ስልክ ቁጥርዎን ያስገቡ',
  phonePlaceholder: 'ለምሳሌ፦ 0912345678',
  continueBtn: 'ቀጥል ›',
  shopNameLabel: 'የሱቅ ስም',
  shopNamePlaceholder: 'የሱቅዎን ስም ያስገቡ',
  gpsActive: '📍 የሱቅ GPS ተይዟል ✓',
  gpsInactive: '📍 የሱቅ አድራሻ (GPS) መዝግብ',
  otpLabel: 'የኤስኤምኤስ (SMS) 4 አሃዝ ኮድ',
  signInBtn: 'ግባና ጀምር',
  topBarTitle: 'ገበያ - አዳማ',
  logOut: 'ውጣ',
  categoriesTitle: 'የምርት ምድቦች',
  ledgerTitle: 'የደንበኞች የብድር መዝገብ (Micro-ERP)',
  ledgerEmpty: 'ምንም የተመዘገበ የብድር መረጃ የለም',
  ordersTitle: 'የትእዛዝ ሁኔታ እና ደረሰኝ',
  ordersEmpty: 'ምንም ንቁ ትእዛዝ አልተገኘም',
  profileTitle: 'የሱቅ መረጃ እና ምርጫዎች',
  profileLang: 'ቋንቋ: አማርኛ / Afaan Oromoo / English',
  tabShop: 'ገበያ',
  tabLedger: 'ሂሳብ',
  tabOrders: 'ትእዛዝ',
  tabProfile: 'መገለጫ',
};

export const CATEGORIES = [
  { id: '1', name: 'ግሮሰሪ እና ባልትና', sub: 'የምግብ እህሎችና ዘይት', icon: '🛒' },
  { id: '2', name: 'የጽዳት እቃዎች', sub: 'ሳሙና እና ዲተርጀንት', icon: '🧽' },
  { id: '3', name: 'ለስላሳ መጠጦች', sub: 'ውሃ እና ጭማቂዎች', icon: '🥤' },
  { id: '4', name: 'መክሰስ እና ጣፋጭ', sub: 'ብስኩት እና ከረሜላ', icon: '🍬' },
  { id: '5', name: 'የትምህርት መሳሪያዎች', sub: 'ደብተር እና እስክሪብቶ', icon: '✏️' },
  { id: '6', name: 'የግብርና ምርቶች', sub: 'ድንች፣ ሽንኩርት እና ጥራጥሬ', icon: '🥔' },
  { id: '7', name: 'የማሸጊያ እቃዎች', sub: 'ፌስታል እና ካርቶን', icon: '📦' },
  { id: '8', name: 'ሲጋራ እና ክብሪት', sub: 'የትምባሆ ውጤቶች', icon: '🚬' },
];